### ISSUE TITLE
Getting the twitchclientid from the default server leads to 404.

### ISSUE THREAD

**Issue by viroulep** [Hyphen-ated/RebirthItemTracker#109]
I get a 404 here : http://kanye.space:8000/tracker/api/twitchclientid.

Shouldn't this server be working ?

**Comment by Zamiell** [comment]
I think the server isn't using the latest commit of the server code, since Hyphen wants to keep it in sync with what the released v1.0 of the client item tracker expects to be there.

**Comment by viroulep** [comment]
Oh right, thanks :)
