### ISSUE TITLE
Adds English (US) keyboard to windows.

### ISSUE THREAD

**Issue by FakeKitten** [Hyphen-ated/RebirthItemTracker#112]
Whenever I open the tracker it adds English (United States) keyboard to windows settings. But it only appears in the taskbar button in windows settings it doesn't appear to be there and can only be removed by adding it though windows settings then removing it again.

This is extremely annoying to me as if I ever accidently  press win + space windows will change me to shitty keyboard layout without my knowledge and the only real solution is to manually add and remove eng-US every time I launch tracker. Also this took me a crazy amount of time to hunt down the source of the magically appearing eng-US layout... :(

Here's a short video of the issue if what I explained above makes me sound like a crazy person;
https://youtu.be/Lxw4817BaBA

**Comment by Hyphen-ated** [comment]
Do you get the same issue when running dist/item_tracker.exe directly rather than using the shortcut called "Launch Item Tracker"?

As a workaround for the win+space problem, you can remove that shortcut in the language bar settings

**Comment by FakeKitten** [comment]
I still have the issue when launching item_tracker.exe manually.

Tried disabling the hotkey using [this guide](http://www.digitalcitizen.life/introducing-windows-8-how-switch-between-keyboard-input-languages). Didn't work, win+space still switches languages.

**Comment by Hyphen-ated** [comment]
I reproduced the issue and it still happens with the following very minimal program

`import pygame`
`pygame.init()`

So it doesn't look like there's much we can do about it without removing our use of pygame

**Comment by Hyphen-ated** [comment]
Which version of Windows are you using?

**Comment by FakeKitten** [comment]
Thanks for trying to help. Seems like I have to live with this pain.

I'm using windows 10 anniversary update.
