### ISSUE TITLE
Old Bandage icon wrong displaying

### ISSUE THREAD

**Issue by Birdie0** [Hyphen-ated/RebirthItemTracker#113]
This is occur when item glow is disabled.
![2016-10-14 18_39_36-](https://cloud.githubusercontent.com/assets/7945905/19393498/948ab9d8-923d-11e6-9209-0ca9ef184663.png)

**Comment by Birdie0** [comment]
Color depth is 8. I convert it to 32 and it's looks fixed.
![collectibles_219](https://cloud.githubusercontent.com/assets/7945905/19399232/323c62e2-9259-11e6-9c50-2672008fbb65.png)
![2016-10-14 22_01_18-clipboard](https://cloud.githubusercontent.com/assets/7945905/19399345/bf63269c-9259-11e6-912f-b17cddb648e6.png)
I heard some others items have same problems. Maybe better convert all items pictures to 32 bit color depth.

**Comment by Hyphen-ated** [comment]
done
