### ISSUE TITLE
Since 1.2.3 the ItemTracker don't run with Afterbrith 

### ISSUE THREAD

**Issue by SancezZ** [Hyphen-ated/RebirthItemTracker#119]
Hi 

I tried the first  time the ItemTracker.
I downloaded the version 1.2.3 and run it. 

I saw the window and it told me that he dont found an Afterbirth+.
This is correct i only have Afterbirth installed. 

I modified it via the configuration editor from Afterbirth+ to Afterbirth.

I reruned the application and it crashed instandly -.-

So after different tries im not able to run this version on my environment. (Windows 10)

The previous version 1.2.2 works like a charm.

**Comment by Hyphen-ated** [comment]
When it crashes, do you get anything in tracker_log.txt?

**Comment by SancezZ** [comment]
Traceback (most recent call last):
  File "item_tracker.py", line 241, in main
  File "item_tracker.py", line 217, in run
  File "view_controls\view.py", line 211, in draw_state
AttributeError: 'TrackerState' object has no attribute 'version_number'

**Comment by Hyphen-ated** [comment]
Does this beta version fix the problem for you?
https://dl.dropboxusercontent.com/u/43223956/RebirthItemTracker-1.2.4-beta1.zip

**Comment by SancezZ** [comment]
The beta works for me.
