### ISSUE TITLE
High DPI monitor compatibility

### ISSUE THREAD

**Issue by VineST** [Hyphen-ated/RebirthItemTracker#134]
When I use this with my monitor (set at 125% UI scaling) the rendered items have a blurry, interpolated look. This makes it pretty difficult to chroma key correctly. Ideally, the window would always render at a 1:1 pixel ratio? Not sure how feasible this would be to correct, but it would be marvelous if possible.

**Comment by Hyphen-ated** [comment]
What OS are you using, and where exactly is its 125% UI scaling option?

**Comment by VineST** [comment]
Not sure why I didn't see this earlier, but this is on Windows 10 with the default scaling from its settings.

**Comment by Hyphen-ated** [comment]
I'm a little confused by your wording. Do you mean your OS scaling is on its default setting, and that you weren't making a silly error when talking about a UI scaling setting on your *monitor*? I've never heard of a UI scaling setting on a monitor, or a monitor setting that could be detected or reacted to by software on the machine itself.

If you did mean that your Windows 10 scaling settings are what's actually on 125%, then you're going to have to tell me exactly where that setting is if you want any help. I am not familiar with where any options are in Windows 10.

**Comment by VineST** [comment]
![image](https://user-images.githubusercontent.com/6686964/33520518-25fe7a78-d782-11e7-97a8-fc134c90baa8.png)
I have a high-DPI monitor which, through the Windows settings menu, receives scaled output.

**Comment by VineST** [comment]
![image](https://user-images.githubusercontent.com/6686964/33520601-f56930ea-d783-11e7-8ed4-aefbbf9da419.png)
This is what my tracker looks like—you can see the interpolation around the text pretty clearly.

**Comment by Inschato** [comment]
Hi @VineST can you try right clicking on `Rebirth Item Tracker.exe`, selecting `Properties` -> `Compatibility` and checking on the setting for `Override high DPI scaling behavior` to `Application`
![override_scaling](https://user-images.githubusercontent.com/4562151/33522267-756693aa-d79d-11e7-99b2-9e415e1c79b4.png)

The tracker itself has a scale option so if that ends up being too small for you, you can tweak it there.

**Comment by VineST** [comment]
I wholly never knew that was a feature. Thanks for the heads-up!
