### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by Gamerbiomek2** [Hyphen-ated/RebirthItemTracker#142]
Traceback (most recent call last):
  File
"C:\Python27\lib\sit-packages\cx_Freeze\initscripts\console.py", line 27 <module>
  File "bootstrapper.py, line 3, in <module>
  File "c:\python\32-bit\2.7\lib\os.py", line 314, in execl
OSError: (Emmo 2) No such file or directory

**Comment by Hyphen-ated** [comment]
Are you attempting to run the program directly out of the zip file without extracting the whole thing somewhere first?

**Comment by Gamerbiomek2** [comment]
no, I just hit the update button

**Comment by Gamerbiomek2** [comment]
I just redownloaded it and it works now lol
