### ISSUE TITLE
how to make a transparent background

### ISSUE THREAD

**Issue by Darnelo-Inc** [Hyphen-ated/RebirthItemTracker#154]
how do I make a transparent background in this app? I tried to put green (0,255,0) and chromakey, but the items still show green pixels somewhere around the edges.

**Comment by Hyphen-ated** [comment]
That's how you do it. The tracker doesn't offer a way to do it flawlessly with something like a browser capture, sorry. Try turning Key Color Spill Reduction way up in your chromakey settings, set Similarity to the minimum, and also play with the Smoothness setting.

**Comment by Darnelo-Inc** [comment]
> That's how you do it. The tracker doesn't offer a way to do it flawlessly with something like a browser capture, sorry. Try turning Key Color Spill Reduction way up in your chromakey settings, set Similarity to the minimum, and also play with the Smoothness setting.

thank you for advice
