### ISSUE TITLE
Have ItemTracker stay open when tabbing out

### ISSUE THREAD

**Issue by samomes** [Hyphen-ated/RebirthItemTracker#159]
Maybe a stupid question, but how do I make the Tracker stay on my Isaac screen when I actually tab into the game? It just closes as most programs would, but I want it to stay atop my game as a layout, just like the LiveSplit timer.

**Comment by Hyphen-ated** [comment]
It's not intended to go on top of the actual game. Typically people either put the tracker on a second monitor or run the game in a window and put the tracker beneath it.

**Comment by samomes** [comment]
Oh, dang. I saw people on streams have the Tracker HUD on top of their game so I assumed it's a built in feature. Really appreciate the info!
