### ISSUE TITLE
Making so tracker tracks spacebar items

### ISSUE THREAD

**Issue by timppaliisa** [Hyphen-ated/RebirthItemTracker#16]
it could really help if it would track spacebar items (or only books if you want to do it that way)... would help with the library books (if you have ton of books toughed you want to reroll books for item room items, if not you dont want to waste a reroll in the library)

**Comment by Inschato** [comment]
https://www.dropbox.com/s/60lkwdn6zhpyxwv/items.txt?dl=0

Replace your items.txt in the tracker folder with the one from the above link to enable showing spacebar items. Note that guppy's head and guppy's paw are already shown by default for the purpose you describe anyway.

**Comment by Hyphen-ated** [comment]
option to track space items is in
