### ISSUE TITLE
Show character stats

### ISSUE THREAD

**Issue by Hyphen-ated** [Hyphen-ated/RebirthItemTracker#23]
damage, speed, etc (it would not calculate your actual tear damage with multipliers and whatnot)

**Comment by viroulep** [comment]
If you imagine this as a line of text displaying the starting character name + base stats, then I can handle this.

**Comment by Hyphen-ated** [comment]
Hm maybe the word "character" in the title here was ill-chosen, I meant an updating total of your stats, given all the items you've picked up. I don't really see the point of having static text based just on your starting character.

I'm not sure exactly the right way to do this though. Ideally we would know precisely how all the item interactions worked, and we could display true damage and dps values like on http://hyphen-ated.github.io/rebirthDps/

But there are interactions that I don't really know how they work, like some combinations that involve chocolate milk, libra, soy milk, or doctor fetus. On the calculator page I just don't include those items, but in the tracker I don't know what the right thing to do is when someone takes one. I don't want the tracker to lie about things, but just taking the numbers away when they take certain items doesn't seem right either.

**Comment by viroulep** [comment]
Oh ok I misunderstood the "it would not calculate ..." part !

Displaying the starting character may be useful for the viewers, but I agree that displaying static base stats is not very interesting...

Additionally to the interactions you mentioned, if the tracker would display true stats, we would also need a way to track player's life because of some items like whore or bloody lust, and I don't see how this is possible by only looking to the log file (we would also have a similar issue for trinkets).

Basically there is 3 options here : 
- Implement an exact computation of player's stats
- Implement a computation to the best of current knowledge, and eventually warn the user when he picks up something we can't handle properly.
- Drop the feature

Unless I'm missing something, option 1 seems impossible to me with the information available in the log (even if we assume perfect knowledge of every interactions).

I'd personnaly go for option 2, with some special warning or coloration when things get out of control.

Actually it would be sweet to combine this with #25, by making "damage", "tears", etc as possible variables. It would also be nice to have a specific coloration when stats cap are reached.

**Comment by Hyphen-ated** [comment]
Yeah displaying some kind of "not sure" indicator could be good. I don't really like the idea of using color though, because it seems very nonobvious for stream viewers what the colors mean. Maybe a question mark at the end, or a tilde at the front.

By "not calculate" i meant if you picked up a +1 damage item, it would show "+1" and not "5.19"

Maybe it's good enough to just add together the numbers that are already in items.txt and display those total values. When do we add a question mark though? when they take ANY item that changes their damage in a way besides a simple addition? which would include coal, money=power, magic mush, tech 2, and whore, but would not include 20/20, quad, or brimstone?
That seems kind of excessive, but I haven't been able to think of a consistent system that I like more than that.

**Comment by viroulep** [comment]
We could go for displaying only raw numbers, but I think some more calculations could be made.

I think for coal/$$/whore we are screwed, but as they guarantee a damage up on their own I would go with a '+' at the end of the calculated value to indicate that it has at least this value.

For magic mush-like item we could still dynamically do the math for the damage per tear.
For 20/20-like we should probably make available both damage per tear and the max damage per shot they could get (?).

For unclear interactions, '~' looks good, even if it seems to imply that the calculated stat is actually close to the real one.
If we assume the spreadsheet maintained by twinge is accurate, there is actually a lot of cases covered, even values on how Libra balances the stats.

For a start we could identify items which may imply tricky interactions, and do the calculations ignoring them (and add the '~').

I don't know, it looks like the information available is enough to display an accurate computation for most runs, so I guess users would be interested in having this feature, at the cost of inaccuracy sometimes.

An other issue is Eden, it's very sad his base stats are not logged...

**Comment by viroulep** [comment]
Could you please take a look at this : 4396598d152c0b7eea703a72ec2e6a05fa35f59e ?
(It's the dps_calculator branch of my fork, but I don't think it's ready for a PR yet)

I tried to implement the dps calculator in the tracker, I may have overlooked how some special items interact with each others, but basically I took information from both your repository and twinge's spreadsheet.
There is some differences between the two, for example the knife multiplier which is 2*dmg per tick for melee in the spreadsheet, and 6 in your repository. I took the spreadsheet value but this may need some tweaking.

The numbers in the spreadsheet for Libra seem wrong though, I did some tests with basic Isaac + Libra, and his stats seems to remain as they were originally.
I did some further test with soy milk + libra on basic Isaac, it took me 11 tears to kill monstro, giving between 22.72 and 25 damage per tear. Using Isaac starting stats as reference to balance the stat, I computed 21.16 damage per tear, which is pretty close. I don't know were the difference comes from, but this is closer than using the 1 dmg = 2.5 range = 0.5 speed indicated in the spreadsheet. Do you know how these numbers were found ?

Anyway, I'm not a guru of Isaac's internal, so any feedback/advice/correction would be greatly appreciated.

**Comment by Zamiell** [comment]
Also note that any shown stats will be incorrect if the player uses any stat up/down pills, since it doesn't say in the log what kind of pill was used.

**Comment by Hyphen-ated** [comment]
I added some basic stat tracking that just adds up the numbers we have in items.txt and doesn't do anything fancy. I looked at 4396598d152c0b7eea703a72ec2e6a05fa35f59e and I'm too worried about showing wrong numbers to use it

**Comment by viroulep** [comment]
I assume you are already aware of that project but this tool displays precise in-game stat : https://github.com/networkMe/missinghud2

**Comment by sillypears** [comment]
Yes, @viroulep it reads from ingame memory and uses a DLL hook to inject into the overlay. You can see the same stats with cheat engine :)

**Comment by viroulep** [comment]
Yep, just wanted to put it here in case someone is passing by wondering how to do this.
The project has no linux port though, unfortunately.

**Comment by Hyphen-ated** [comment]
I guess this is as finished as it's realistically going to be
