### ISSUE TITLE
customizable text display

### ISSUE THREAD

**Issue by Hyphen-ated** [Hyphen-ated/RebirthItemTracker#25]
have a thing where you can configure what goes into the display, like
"Seed: %seed% - Guppy: %guppy% - Special: %special%"
so people can swap around the order or labels

**Comment by viroulep** [comment]
The easiest way to do this is probably to have the user format the string like this : 
"I'm using the seed {seed}, guppy ? {guppy}"
so that it's directly possible to use named parameters when formatting the final string.
Would this be fine for you ?
