### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by HarlequinNight** [Hyphen-ated/RebirthItemTracker#29]
Hi, hope I am submitting this correctly. Random twitch viewer here.

Issue: 
item_tracker v0.6 occasionally stops tracking items and pops up an error window in the background saying errors have occurred and check the log file. Error Pictured
![isaac tracker errors](https://cloud.githubusercontent.com/assets/13692499/9133011/059060de-3cc6-11e5-9e11-62d47f3476e5.PNG)

The log file then contains the following:

Traceback (most recent call last):
  File "item_tracker.py", line 611, in < module>
  File "item_tracker.py", line 472, in run
  File "item_tracker.py", line 340, in write_item_text
IndexError: list index out of range

Hope this is useful, but perhaps I am just doing something wrong.

**Comment by Hyphen-ated** [comment]
Thanks for the report. I think this has been fixed in the latest version (which isn't out yet but should be sometime soon)
I think it might be triggered by having the mouse on top of the icons when you reset a run in rebirth, so you could try avoiding that as a workaround.

**Comment by HarlequinNight** [comment]
Excellent, thanks Hyphen-ated ^_^

**Comment by HarlequinNight** [comment]
Just FYI in version 0.7 I still occasionally see the item tracker stop tracking with the same error popup. The log entry repeated is below, only the line is different from last time:

Traceback (most recent call last):
  File "item_tracker.py", line 706, in <module>
  File "item_tracker.py", line 532, in run
  File "item_tracker.py", line 367, in write_item_text
IndexError: list index out of range

Typically I am running Isaac on monitor 1, windowed, with the item tracker. window 2 is usually twitch, and other browsers etc.

The only change I usually make to item tracker is that I put the message duration to 600 so I can read the last item description effectively forever.

**Comment by Hyphen-ated** [comment]
I had missed a case in my fix before, tried again and hopefully did a better job this time.
(reopen if still broken in next release)

**Comment by HarlequinNight** [comment]
Thank you kindly ^_^
