### ISSUE TITLE
Wrap the top text and line up the items

### ISSUE THREAD

**Issue by Brett824** [Hyphen-ated/RebirthItemTracker#3]
`<Inschato> Since we're on the topic of the text, I also noticed that maybe if the seed/desc are disabled, the items should align to the top of the window`

We just have the height of the padding added right now, could do a simple (but inelegant) check to not add that

`<+_910dan> can you have setting where it wraps the text if people want it horizontal`

This one is harder, but it also benefits from not having the text height padding not hardcoded.

**Comment by Brett824** [comment]
@Hyphen-ated I implemented this, but I don't know how or if the new .py file I added needs to be included for the .exe building.

**Comment by Hyphen-ated** [comment]
you don't have to do anything, it works
