### ISSUE TITLE
RebirthMapTracker

### ISSUE THREAD

**Issue by Glaived** [Hyphen-ated/RebirthItemTracker#31]
Hi,

you think it would be possible to create this software?

![animation 0](https://cloud.githubusercontent.com/assets/1835170/9358824/4df1272e-468e-11e5-8716-48b07563528c.gif)

**Comment by Hyphen-ated** [comment]
well it's certainly possible but I'm not sure how a good a fit it is with how the tracker works right now

**Comment by Hyphen-ated** [comment]
no i don't think so
