### ISSUE TITLE
DeadCat Count

### ISSUE THREAD

**Issue by Glaived** [Hyphen-ated/RebirthItemTracker#32]
Hi,
is it possible to add a DeadCat counter for remaining the number of life?

**Comment by Hyphen-ated** [comment]
i don't understand why you want this, it's already displayed inside the game isn't it?

**Comment by OdnetninI** [comment]
The lost / Unknown Curse

**Comment by Hyphen-ated** [comment]
death info isn't in the log anyway so this isn't going to happen unless we move to a memorywatch system
