### ISSUE TITLE
Afterbirth Compatability

### ISSUE THREAD

**Issue by Zamiell** [Hyphen-ated/RebirthItemTracker#46]
If the player picks up an item that isn't in the items.txt file, the tracker should not crash. Instead, it should just display a Curse of the Blind "?" icon.

This change should allow the vanilla tracker to work with Afterbirth "out of the box".

**Comment by courajs** [comment]
Or some afterbirth icon, like a hanging shopkeeper or some such. Hover can say something like Afterbirth is out?!?!! We're working on support

**Comment by Zamiell** [comment]
I'm assuming I should wait until the other PR is merged before I start implementing this, since the fix will be different in both version.
