### ISSUE TITLE
Missing the "Arial" font

### ISSUE THREAD

**Issue by HoratioSanchez** [Hyphen-ated/RebirthItemTracker#5]
Traceback (most recent call last):
  File "item_tracker.py", line 452, in <module>
  File "item_tracker.py", line 301, in run
  File "pygame\sysfont.pyo", line 577, in SysFont
IOError: unable to read font filename

no idea how to fix it

**Comment by Hyphen-ated** [comment]
How are you running the tracker? using the exe from a released zip, or with python directly?

**Comment by HoratioSanchez** [comment]
exe from the zip

**Comment by Hyphen-ated** [comment]
Try downloading this font and putting it in the directory with the exe http://dev.w3.org/cvsweb/~checkout~/Amaya/fonts/FreeSansBold.ttf?rev=1.1;content-type=application%2Foctet-stream

If that doesn't work, try installing it in windows by double clicking it to open in the windows font viewer and hitting "install"

**Comment by HoratioSanchez** [comment]
I tried both methods and did a fresh reboot and still no luck, getting the same exact error.

**Comment by Hyphen-ated** [comment]
Oh actually the font should just be Arial. Do you not have Arial on your system?

**Comment by HoratioSanchez** [comment]
I'm on Win7 64bit and I have "Arial Regular", but not "Arial".

**Comment by HoratioSanchez** [comment]
Hah! That actually fixed the issue. I went ahead and downloaded this pack and it replaced my Arial Regular with just plain Arial https://www.microsoft.com/en-us/download/details.aspx?id=16083 and now it works. Thanks man!
