### ISSUE TITLE
Show Curse Blind Crashes Program

### ISSUE THREAD

**Issue by DeejStar** [Hyphen-ated/RebirthItemTracker#56]
When enabled, after I get a curse of the blind floor, the program completely crashed and wouldn't load up again.

'NoneType' object has no attribute 'floor_has_curse'

I solved the issue by just commenting out lines 344 - 347 in the view.py file since those were the offending lines of code.

**Comment by viroulep** [comment]
Was it in normal/hard mode or greed mode ?
The latter is unsupported yet.

If it's the former, it would be perfect if you have the log file :)

**Comment by DeejStar** [comment]
It was actually in all modes. Here's my logs

https://www.dropbox.com/s/4bcconk3h53pkxt/run_logs.zip?dl=0

**Comment by viroulep** [comment]
Thanks, among all the logs in the zip only one seed had a blind floor (HZ1JZXRD, the one with cursed eye taken blind in womb), and I can run the tracker fine on all the log it output.
If you confirm this is the run you're talking about my guess is that the tracker crashed before writing the log.

I assume you used the partially updated tracker for afterbirth ?
If you didn't restart your game you might still find the game log file in Documents/My Games/Binding of Isaac Afterbirth, quite unlikely though.

I thing @sillypears got a similar bug report from Ou_J, with the game log, we may be able to fix it with it.
