### ISSUE TITLE
Items are "forgotten" if you quit and continue

### ISSUE THREAD

**Issue by Zamiell** [Hyphen-ated/RebirthItemTracker#58]
Pretty sure that this is a new bug with Afterbirth. Did the tracker work this way before?
And what would be the best way to fix this?

**Comment by viroulep** [comment]
I remember it dropped the items when you would actually close the game, but not when you would just exit/continue.

We should probably look at how the game logfile behave when doing this, and see if it comes from it or from the caching system in the tracker.

**Comment by DrSilence** [comment]
As far as i can see it is a tracker problem:

line 99,100 & 473-475 from item_tracker.py:

``` javascript
...
 99            elif (self.seed != '') and line.startswith('RNG Start Seed:'):
100                end_type = "Reset"
...
473                    if line.startswith('RNG Start Seed:'): # The start of a run
474                        self.seed = line[16:25] # This assumes a fixed width, but from what I see it seems safe
475                        self.start_new_run(current_line_number)
...
```

'RNG Start Seed:' occur on new runs as well as in continued runs. Only way to see if it is a real new run is to check if a "generate..." occur before entering first 'Room '.
Unfortunately in continued runs i dont get the 'Add Item' lines for already picked up items.

I hope this will help :)

**Comment by Hyphen-ated** [comment]
"generate..." also appears before entering the first room on later floors, so that's not really any good. maybe we should trigger on "Level::Init m_stage 1"

**Comment by Hyphen-ated** [comment]
that seems to work
