### ISSUE TITLE
Glowing Hourglass + X

### ISSUE THREAD

**Issue by viroulep** [Hyphen-ated/RebirthItemTracker#59]
If you activate the hourglass right after taking an object, the object remains in the tracker even if the character don't have it anymore.

I don't know how to fix this though...

**Comment by Hyphen-ated** [comment]
There's nothing at all in the log that can get us to the right answer here. I don't think we can do anything

**Comment by Zamiell** [comment]
From what I understand, when the Glowing Hourglass is activated, no log entry is generated.
Add a section to the README.md file called "Known Bugs" and put this there, then close this issue.
