### ISSUE TITLE
Completing the angel key crashes the tracker

### ISSUE THREAD

**Issue by Hyphen-ated** [Hyphen-ated/RebirthItemTracker#60]
7:33 PM - Smite: had a combo that makes your tracker crash, not sure what it was but i got it on tape somewhere
8:47 PM - Smite: looks like the key completion caused it both times. I did cheat to get the key out of one angel room though
8:48 PM - Smite: by going back to menu and resuming

I haven't investigated yet

**Comment by Hyphen-ated** [comment]
could not reproduce

**Comment by viroulep** [comment]
Did he say what kind of crash it was ?
Sounds like something we could have fixed lately as we fixed a bunch of quit/resume issues.

**Comment by Hyphen-ated** [comment]
He doesn't know what kind of crash it was. I was trying to reproduce it in 0.8 not the latest master.
I talked to him more and he said that at a certain point the tracker was crashing instantly when he launched it, but later it worked fire. Sounds like it was happening consistently with that specific log.txt. Unfortunately it seems like the crash stopped it from being written to run_logs

**Comment by Hyphen-ated** [comment]
log.txt of the event here: http://pastebin.com/MU5EfLrr
I reproduced it in 0.8 and it doesn't crash in the latest code, so it seems fixed
