### ISSUE TITLE
Guppy tracker broken

### ISSUE THREAD

**Issue by p00rleno** [Hyphen-ated/RebirthItemTracker#63]
Seems to consider items that are not guppy, to be guppy. See http://i.imgur.com/QnWgdJn.png for example. I know one item that incremented the counter that should not have was Growth Hormones.

**Comment by Zamiell** [comment]
Looks like the 4GLY ZWZT. I'll try to replay it and find the bug.

**Comment by viroulep** [comment]
Ok so I looked into this, it's just because the guppy's paw was added twice to the guppy set, because the Item's **hash** method was not implemented according to Item id.
You can trigger the bug by taking mom's pad on the left of the starting room, and taking again Guppy's paw.
