### ISSUE TITLE
Tracker sometimes goes way offscreen

### ISSUE THREAD

**Issue by Hyphen-ated** [Hyphen-ated/RebirthItemTracker#64]
My power went out and when I tried to run the tracker afterward, my options.json contained:

"x_position": -31996, 
"y_position": -31977

and so the tracker was not visible. a few people have complained about the tracker not being visible before and I'm guessing this is what they were seeing.

maybe there's some way we can prevent this from happening

**Comment by Zamiell** [comment]
Perhaps include this logic at program intialization:

```
if x_position + width < 5 && y_position + height < 5:
    reset_window_position()
```

**Comment by Hyphen-ated** [comment]
i put in something similar
