### ISSUE TITLE
Cant make shortcut on desktop

### ISSUE THREAD

**Issue by XCGAMES** [Hyphen-ated/RebirthItemTracker#66]
I already move the folder to the rebirth one and if i open it on the folder it works but if i make a shortcut to the desktop it says that windows cannot find 'dist/item_tracker.exe'

**Comment by Hyphen-ated** [comment]
I think this was fixed in 0.9
What version are you using?

**Comment by XCGAMES** [comment]
0.9

**Comment by sillypears** [comment]
I just tested it and it in fact does not work (I get the same error). I'm not sure how you'd create a shortcut, other than creating a shortcut of the shortcut with the same parameters in it, that can be moved out of the folder, since the starting directory would have to be set to wherever you put the tracker folder.

By default I believe it looks like this:

"C:\Users<username>\Documents\My Games\Binding of Isaac Afterbirth\RebirthItemTracker-0.9"

**Comment by FunkyMiller** [comment]
Only way I got it to work was copying the shortcut, but it had to be copied to a parent location of the install folder, as the passed in relative location of the folder doesn't seem to reference the "start in" location

**Comment by XCGAMES** [comment]
Yep, i tried to make a shortcut of the shortcut but how it didnt work i made a shortcut of the folder to the desktop for  now while this error is fixed.

Yes by the default that was where the folder was but i moved to the rebirth folder hoping it would be fixed there, but it didnt work.

**Comment by Hyphen-ated** [comment]
It works if you make a shortcut to item_tracker.exe (the one in the dist folder) rather than making a shortcut to the shortcut. this should be in the documentation i guess. 
it doesn't matter where you put the tracker folder. you don't have to do anything special to the shortcut you make.

**Comment by sillypears** [comment]
I also did the above that @Hyphen-ated mentioned and it did work. I guess it should be documented if you want to create on your desktop or some other location, you need to make it based off the .exe file and not off the provided shortcut.

**Comment by Zamiell** [comment]
Hyphen - add this information to the readme and then close this issue?

**Comment by Hyphen-ated** [comment]
it is done
