### ISSUE TITLE
Overlay on the game

### ISSUE THREAD

**Issue by avolden** [Hyphen-ated/RebirthItemTracker#7]
Hello Hyphen-ated
I saw someone with an overlay like that but I don't know how he did
![capture](https://cloud.githubusercontent.com/assets/11920536/7896119/159445ba-06af-11e5-8d02-31a872482ab7.PNG)
Do you know how he did ? And if yes, how I can do to have the same ?

**Comment by Hyphen-ated** [comment]
You set the background of the tracker to a bright color (by right clicking), then use chromakey in OBS to mask out that color
