### ISSUE TITLE
Has the caching system been tested ?

### ISSUE THREAD

**Issue by viroulep** [Hyphen-ated/RebirthItemTracker#76]
Just in case I overlooked something in #75, did anyone test the caching system in the view ?

Without the `__hash__` function being implemented, two items with identical id will likely not have the same hash, and therefore be duplicated in the set of cached item, which actually means that there is no cache (worse, items from all previous runs are stored !).

Thoughts ?

**Comment by Hyphen-ated** [comment]
i feel like we should remove this cache. i don't see how it's buying us much to make up for the complexity it introduces

**Comment by viroulep** [comment]
I also don't see how this cache is helping much.
Python has a garbage collector, so if we correctly clean all references to run-specific object at the beginning of each run, the GC should do his thing.

**Comment by viroulep** [comment]
Additionally to this, keeping a "drawn_item" member in the view causes wrong display of rerolled items.
For example start as the lost, reroll the mantle, and after a reset the mantle is still tagged as rerolled.
I'm going to fix all this while I adress #40 .
