### ISSUE TITLE
New GUI Cleanup

### ISSUE THREAD

**Issue by Zamiell** [Hyphen-ated/RebirthItemTracker#86]
Greying out options is confusing for the end-user. "Why is this option greyed out? Did I misconfigure something? Did I do something wrong?" Not to mention it seems a little sloppy.

1) By default, all of the tournament settings (besides the 2 buttons) should be hidden if both of them are disabled. By pressing a button, now all of the settings appear.
2) When in competitor mode, "Twitch Name" and "Read Delay" should not show up at all.
3) When in host mode, "Trackserver Authkey" and "Get an authkey" should not show up at all.

**Comment by Hyphen-ated** [comment]
seems better

**Comment by Hyphen-ated** [comment]
i removed disabling in favor of appearing and disappearing. i also moved the server stuff to the side because i thought it looked better.

does it satisfy you, zam

**Comment by Zamiell** [comment]
Yes, it looks much better now, I'll close this.
