### ISSUE TITLE
Make the graphics better for the collectible items

### ISSUE THREAD

**Issue by Zamiell** [Hyphen-ated/RebirthItemTracker#87]
Currently, all of the collectible images for the tracker are taken from the in-game images. In them, all of the items have a 1 pixel black border to them.

This works fine for the most part, with a few exceptions:
- Judas' Shadow, item #311 - a completely black item
- My Shadow, item #433 - a completely black item

These items aren't visible with a pure black background, which is semi-common in stream layouts. Furthermore, even items that aren't completely black don't look very good on a black background. For example, notice the contrast on the D6 and Incubus:

http://i.imgur.com/7lSbJMg.png

One easy fix is to simply add a border to the PNG files for Judas' Shadow and My Shadow and call it a day. However, a much better solution to make all of this look a lot nicer is to draw shadows or semi-transparent borders around the items. This is what is done on the Balls of Steel item tracker. Here's a picture of it in action:

http://i.imgur.com/PC6W5NP.png

I'm a huge fan of this and I believe it should be done to this tracker as well. In terms of how to accomplish it, I see two possible ways:

1) All of the PNG image files themselves are modified. Someone proficient with Photoshop can probably do this kind of thing in a batch job? Not really sure, as this isn't my area of expertise.

2) Dynamically draw the borders/shadows in the Python code. For example, see this example using PIL: http://code.activestate.com/recipes/474116-drop-shadows-with-pil/

Thoughts?

Overall, with the recent addition of the tournament feature and more eyes in general on the item tracker, I really think some attention to detail needs to be given in this regard.

**Comment by viroulep** [comment]
I think dynamically applying the same operation to something static is not good performance-wise.

We should probably tweak this python example to our need, apply it on all images and save them.
