### ISSUE TITLE
Mega blast + d12 pedestal swapping results in lots of questionmarks on tracker.

### ISSUE THREAD

**Issue by haagiboy88** [Hyphen-ated/RebirthItemTracker#88]
Swapping out an item pedestal over and over with D12 and Mega blast makes the tracker fill up with ? ? ? ? ?.

Video: http://www.twitch.tv/haagiboy88/v/36561910

**Comment by viroulep** [comment]
I believe that's going to be fixed with the next release : mega blast was not part of the 0.9 release, an unkown item isn't tagged as a spacebar item, therefore the tracker thinks a different unknown item is picked up every time.

**Comment by haagiboy88** [comment]
Yeah I talked to hyphen on stream. I tested it against the beta as well. It
is fixed in the beta :)
