### ISSUE TITLE
Add logic to check to see if the player has Black Candle

### ISSUE THREAD

**Issue by Zamiell** [Hyphen-ated/RebirthItemTracker#90]
Before assigning a curse to the current floor, there should be a check to see if the player has Black Candle in their inventory. If so, then it should NOT assign a curse.

The relevant code is in log_parser.py, line 157:

```
    def __parse_curse(self, line):
        """ Parse the curse and add it to the last floor """
        if line.startswith("Curse of the Labyrinth!"):
            self.state.add_curse(Curse.Labyrinth)
        if line.startswith("Curse of Blind"):
            self.state.add_curse(Curse.Blind)
        if line.startswith("Curse of the Lost!"):
            self.state.add_curse(Curse.Lost)
```

Furthermore, if the player picks up Black Candle, it should remove the "Curse of Blind" curse state for the current floor if it is present.

**Comment by viroulep** [comment]
This is going to work in most case, however it will remove the question mark from previous items picked up on the floor, which were picked up blind.

**Comment by Zamiell** [comment]
One way to fix this is to give each item in the state a "blindPickup" property, and when calculating if we should affix a blind question mark to it, we use the blindPickup property instead of looking to see if the floor is cursed.

**Comment by viroulep** [comment]
Indeed, and that wouldn't be hard to implement.
It will break the serialization compatibility though, so if we want to do this we need to do it before the release to avoid any backward incompatibility.
