### ISSUE TITLE
Add new option for "BLCK CNDL" seed

### ISSUE THREAD

**Issue by Zamiell** [Hyphen-ated/RebirthItemTracker#91]
Add a checkbox to options_picker.py that will disable curse parsing on line 157 of log_parser.py.

(The game will still output curse information to the log.txt even if you have the "Total curse immunity" seed enabled.)

**Comment by Hyphen-ated** [comment]
it needs to be handled in the view not in the log parser. i am doing it

**Comment by Hyphen-ated** [comment]
done
