### ISSUE TITLE
Users get confused about when options are updated

### ISSUE THREAD

**Issue by Hyphen-ated** [Hyphen-ated/RebirthItemTracker#96]
people keep expecting the network options to apply instantly when they change them in the options menu, without clicking save. this doesn't work. so we should either make it clearer that it won't work (black out the tracker window?), or make it actually work, by instantly applying changes but keeping a backup copy of the options in case they click cancel

**Comment by viroulep** [comment]
Maybe we should just update the reamde to document the new feature ?
And highlight with bold+red font the save button when a change is made ?

**Comment by Hyphen-ated** [comment]
haagi explicitly told people multiple times that they needed to click save, and they still didn't do it. a readme won't do the job
