### ISSUE TITLE
Better "Blanked Out" feature

### ISSUE THREAD

**Issue by Zamiell** [Hyphen-ated/RebirthItemTracker#99]
Currently, the item tracker is "blanked out" when the options picker is open. This is to force silly users to click "Save" or "Cancel" on the options picker.

With that said, it is a little confusing as to what is going on for a new user. Have the item tracker draw the following text where the stats message normally goes:

"Please hit either "Save" or "Cancel" on the options window to continue."

**Comment by Hyphen-ated** [comment]
i actually dont see how this is possibly confusing. a huge always-on-top window pops up at the same time as the blackout

**Comment by Zamiell** [comment]
On my computer, the options window pops up on my second montor, way out of sight. If this happened to a user who was not familiar with the tracker, they would be confused.

"I right clicked the item tracker and now everything is blacked out? What is going on?"

**Comment by sillypears** [comment]
In the blank space of the options window now as well, we can put text saying "Options do not get applied until you click save" since there is a bunch of unused space on the right side.

**Comment by Hyphen-ated** [comment]
it seems so clumsy to have to write that. have you ever seen a program that had to write text like that on the screen? it's not like we're breaking new ground in interface design here.

what if we just make the options window consistently open on top of the main window in the first place

**Comment by Zamiell** [comment]
That seems reasonable.

**Comment by Hyphen-ated** [comment]
made the options always open on top of the tracker, and added "Editing options..." message
